#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format.
#   Displays "Fizzbuzz" when number is a multiple of 3 and 5.
#   Displays "Fizz" when number is a multiple of 3.
#   Displays "Buzz" when number is a multiple of 5.
#   Otherwise, display the number.

for num in {1..100}
do
  if (( num % 3 == 0 && nu % 5 == 0 ))
  then 
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  if
done
